settings:
  provider: native

relaychain:
  default_command: ./target/release/orehub-node
  random_nominators_count: 0
  chain: zombie-testnet
  nodes:
    - name: alice
      validator: true
    - name: bob
      validator: true

keystore_key_types:
  - aura_ed
  - gran_ed
  - imon_ed
  - acco_ed
