name: Release

permissions:
  contents: write
  packages: write

on:
  release:
    types: [released]

jobs:
  release-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Free Disk Space (Ubuntu)
        uses: ./.github/actions/free-disk-space

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

  release-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rust compilation prerequisites
        uses: ./.github/actions/ubuntu-dependencies

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build the node
        run: cargo build --locked --release
        timeout-minutes: 90

      - name: Upload the binaries
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/orehub-node
            target/release/wbuild/orehub-runtime/orehub_runtime.compact.compressed.wasm
